### ISSUE TITLE
goog.require could not find: goog.dom.HtmlElement

### ISSUE THREAD

**Issue by royalaid** [jtkDvlp/cljs-workers#2]
I am trying to work with Web Workers right now and have been trying to pull together https://github.com/jtkDvlp/cljs-workers and the guide at https://github.com/bhauman/lein-figwheel/wiki/Using-Figwheel-with-Web-Workers and I have it almost working but when I `(:require [cljs-workers.core :as main])` from my webworker file and load the page I get back `goog.require could not find: goog.dom.HtmlElement`.

**Comment by royalaid** [comment]
Just to update on this it appears to stem from the use of core.async, not sure how but explicitly requiring core.async in an otherwise empty worker breaks the ability to load the worker after cljs compiles

**Comment by jtkDvlp** [comment]
Hi royalaid,

first of all thx for your issue.

As you probably already know, the error occours because there is no DOM within the worker context, though some line of code within the worker presupposes it.

I do not know the "figwheel with Web Worker" guide. I will try it myself with the guide and hopefully find the issue.

During you are waiting, do you could verify whether it works for you with a compiled version of your worker via cljsbuild?

**Comment by royalaid** [comment]
I have tried with cljsbuild as well and no luck. I have also tried with the various different kinds of optimizations and that doesn't seem to work either. If you are able to get https://github.com/bhauman/lein-figwheel/wiki/Using-Figwheel-with-Web-Workers off the ground try requiring core.async or cljs-workers in [worker.cljs](https://github.com/yetanalytics/figwheel-worker-example/blob/master/src_worker/figwheel_worker_example/worker.cljs) and it should replicate the issue.

**Comment by jtkDvlp** [comment]
I make a fork of the "figwheel-worker-example" and build in my cljs-workers. For me it works. Do you could check what's different to your version, what I'm doing wrong to replicate the issue?

Does the fork also work for you?

**Comment by jtkDvlp** [comment]
The output I'm getting:
```clojure
"I'm a worker and I got bootstrapped!"
"success" {:a "Hello", :b "World!", :c 10, :d "de9a7936-315e-4dde-a870-52d7e7aba278", :worker "I am alive!", …}

```

**Comment by jtkDvlp** [comment]
@royalaid did you solve the problem? Can you tell us your solution?

**Comment by royalaid** [comment]
My fix was to copy the precedent set by the library and just remove the need for core async. This does mean that some of the niceties of the library and any future bug fixes aren't propagated but the trade-off is worth it for us. If you want to try out the code that was causing the bug I can confirm it is reproducible on the project I contribute to [here](https://github.com/goodsoftwareengineering/time-align) specifically in [this file](https://github.com/goodsoftwareengineering/time-align/blob/master/src_worker/cljs/time_align/worker.cljs). As to why we are getting different results with the figwheel example I can't say and unfortunately don't have time to dig into why.
